sim1:
  type: 'rays'
  init:
    dir_sim: '/lightcone/box1/'
    dir_out: null
    file_dsc:
      root: 'Ray_maps'
      extension: 'h5'
    dir_root: null

sim2:
  type: 'rays'
  init:
    dir_sim: '/lightcone/box2/'
    dir_out: null
    file_dsc:
      root: 'Ray_maps'
      extension: 'h5'
    dir_root: null

sim3:
  type: 'rays'
  init:
    dir_sim: '/lightcone/box3/'
    dir_out: null
    file_dsc:
      root: 'Ray_maps'
      extension: 'h5'
    dir_root: null

sim4:
  type: 'rays'
  init:
    dir_sim: '/lightcone/box4/'
    dir_out: null
    file_dsc:
      root: 'Ray_maps'
      extension: 'h5'
    dir_root: null

sim5:
  type: 'rays'
  init:
    dir_sim: '/lightcone/box5/'
    dir_out: null
    file_dsc:
      root: 'Ray_maps'
      extension: 'h5'
    dir_root: null
