sim1:
  type: 'particles'
  init:
    dir_sim: '/cosma6/data/dp004/cubic_vector_galileon/lightcone_cvg_qcdm/box1/'
    dir_out: null
    file_dsc:
      root: 'halos'
      extension: 'ascii'
    dir_root: 'rockstar'
    boxsize: 500.
    domain_level: 512

sim2:
  type: 'particles'
  init:
    dir_sim: '/cosma6/data/dp004/cubic_vector_galileon/lightcone_cvg_qcdm/box2/'
    dir_out: null
    file_dsc:
      root: 'halos'
      extension: 'ascii'
    dir_root: 'rockstar'
    boxsize: 500.
    domain_level: 512

sim3:
  type: 'particles'
  init:
    dir_sim: '/cosma6/data/dp004/cubic_vector_galileon/lightcone_cvg_qcdm/box3/'
    dir_out: null
    file_dsc:
      root: 'halos'
      extension: 'ascii'
    dir_root: 'rockstar'
    boxsize: 500.
    domain_level: 512

sim4:
  type: 'particles'
  init:
    dir_sim: '/cosma6/data/dp004/cubic_vector_galileon/lightcone_cvg_qcdm/box4/'
    dir_out: null
    file_dsc:
      root: 'halos'
      extension: 'ascii'
    dir_root: 'rockstar'
    boxsize: 500.
    domain_level: 512

sim5:
  type: 'particles'
  init:
    dir_sim: '/cosma6/data/dp004/cubic_vector_galileon/lightcone_cvg_qcdm/box5/'
    dir_out: null
    file_dsc:
      root: 'halos'
      extension: 'ascii'
    dir_root: 'rockstar'
    boxsize: 500.
    domain_level: 512
